--- 
- 
   file: 
    group: root
    mode: 755
    owner: root
    path: /opt/pega-chat
    state: directory
   name: "Create a directory"

- 
   name: "Check the stat Path Chat"
   register: pathchat
   stat: 
    path: /opt/pega-chat/chat.tar.gz
- 
  get_url: 
    dest: /opt/pega-chat
    url: "{{pega_chat}}"
    validate_certs: false
  when: pathchat.stat.exists == False
  name: "Download Pega-Chat"
- 
  name: "Check the stat Path Node"
  register: pathnode
  stat: 
    path: /opt/pega-chat/node-*.tar.gz
- 
  get_url: 
    dest: /opt/pega-chat
    url: "{{node_js}}"
    validate_certs: false
  when: pathnode.stat.exists == False
  name: "Download Node Js"
- 
  name: "Check the stat Path MongoDB"
  register: pathmongo
  stat: 
    path: /opt/mongodb-*.tgz
    
- 
  file: 
    group: root
    mode: 755
    owner: root
    path: /opt/Mongo
    state: directory
  name: "Create a Directory Mongo"
- 
  get_url: 
    dest: /opt/Mongo
    url: "{{mongo_db}}"
    validate_certs: false
  when: pathmongo.stat.exists == False
  name: "Download Mongo-DB"
- 
  name: "Download and Install Yum Updates"
  shell: "yum -y  install yum-plugin-downloadonly"

-  
  name: "Download all the necessary dependencies for Mongo"
  shell: "yum reinstall --downloadonly --setopt=protected_multilib=false –downloaddir=/opt/Mongo cyrus-sasl cyrus-sasl-gssapi cyrus-sasl-plain krb5-libs libcurl libpcap lm_sensors-libs net-snmp net-snmp-agent-libs openldap openssl rpm-libs tcp_wrappers-libs rpm openssl-libs net-snmp-libs"


- 
  file: 
   group: root
   mode: 755
   owner: root
   path: /opt/Redis
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat redis"
   register: pathredis
   stat: 
    path: /opt/Redis/redis-*.tar.gz

- 
   get_url: 
    dest: /opt/Redis
    url: "{{redis}}"
    validate_certs: false
   when: pathredis.stat.exists == False
   name: "Download Redis"
   
-  
  name: "Download all Development Tools"
  shell: yum install yum-plugin-downloadonly && yum groupinstall --downloadonly "Development Tools"
 
 
- 
  file: 
   group: root
   mode: 755
   owner: root
   path: /opt/tcl
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat tcl"
   register: pathtcl
   stat: 
    path: /opt/tcl/tcl*-*.tar.gz

- 
   get_url: 
    dest: /opt/tcl
    url: "{{tcl}}"
    validate_certs: false
   when: pathtcl.stat.exists == False
   name: "Download TCL"
   
- 
  file: 
   group: root
   mode: 755
   owner: root
   path: /opt/icu
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat icu"
   register: pathicu
   stat: 
    path: /opt/tcl/icu*-*.tar.gz

- 
   get_url: 
    dest: /opt/icu
    url: "{{icu}}"
    validate_certs: false
   when: pathicu.stat.exists == False
   name: "Download ICU"
  

  
