--- 
- 
   file: 
    group: root
    mode: 755
    owner: root
    path: "{{pega_chat_dir}}"
    state: directory
   name: "Create a directory"

- 
   name: "Check the stat Path Chat"
   register: pathchat
   stat: 
    path: '"{{ pega_chat_dir }}"/chat.tar.gz'
- 
  get_url: 
    dest: "{{pega_chat_dir}}"
    url: "{{pega_chat}}"
    validate_certs: false
  when: pathchat.stat.exists == False
  name: "Download Pega-Chat"
- 
  name: "Check the stat Path Node"
  register: pathnode
  stat: 
    path: '"{{ pega_chat_dir }}"/node-*.tar.gz'
- 
  get_url: 
    dest: "{{pega_chat_dir}}"
    url: "{{node_js}}"
    validate_certs: false
  when: pathnode.stat.exists == False
  name: "Download Node Js"
- 
  name: "Check the stat Path MongoDB"
  register: pathmongo
  stat: 
    path: '"{{ mongo_db_dir }}"/mongodb-*.tgz'
    
- 
  file: 
    group: root
    mode: 755
    owner: root
    path: "{{mongo_db_dir}}"
    state: directory
  name: "Create a Directory Mongo"
- 
  get_url: 
    dest: "{{mongo_db_dir}}"
    url: "{{mongo_db}}"
    validate_certs: false
  when: pathmongo.stat.exists == False
  name: "Download Mongo-DB"
- 
  name: "Download and Install Yum Updates"
  shell: "yum -y  install yum-plugin-downloadonly"

-  
  name: "Download all the necessary dependencies for Mongo"
  shell: "yum reinstall --downloadonly --setopt=protected_multilib=false –downloaddir=/opt/Mongo cyrus-sasl cyrus-sasl-gssapi cyrus-sasl-plain krb5-libs libcurl libpcap lm_sensors-libs net-snmp net-snmp-agent-libs openldap openssl rpm-libs tcp_wrappers-libs rpm openssl-libs net-snmp-libs"


- 
  file: 
   group: root
   mode: 755
   owner: root
   path: "{{redis_dir}}"
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat redis"
   register: pathredis
   stat: 
    path: '"{{ redis_dir }}"/redis-*.tar.gz'

- 
   get_url: 
    dest: "{{redis_dir}}"
    url: "{{redis}}"
    validate_certs: false
   when: pathredis.stat.exists == False
   name: "Download Redis"
   
-  
  name: "Download all Development Tools"
  shell: yum install yum-plugin-downloadonly && yum groupinstall --downloadonly "Development Tools"
 
 
- 
  file: 
   group: root
   mode: 755
   owner: root
   path: "{{tcl_dir}}"
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat tcl"
   register: pathtcl
   stat: 
    path: '"{{ tcl_dir }}"/tcl*-*.tar.gz'

- 
   get_url: 
    dest: "{{tcl_dir}}"
    url: "{{tcl}}"
    validate_certs: false
   when: pathtcl.stat.exists == False
   name: "Download TCL"
   
- 
  file: 
   group: root
   mode: 755
   owner: root
   path: "{{icu_dir}}"
   state: directory
  name: "Create a directory"

- 
   name: "Check the stat icu"
   register: pathicu
   stat: 
    path: '"{{ icu_dir }}"/icu*-*.tar.gz'

- 
   get_url: 
    dest: "{{icu_dir}}"
    url: "{{icu}}"
    validate_certs: false
   when: pathicu.stat.exists == False
   name: "Download ICU"
  
  
-
  name: Extract the Node Package
  shell: tar -xvzf '"{{ pega_chat_dir }}"/node-*.tar.gz'
  when: pathnode.stat.exists == True
  
-
  name: Execute the NVM Install
  command: chdir '"{{ pega_chat_dir }}"/node-*'
  shell: ./install.sh
  

  
